name: Test

permissions:
  contents: write

on: [push]

jobs:
  rust-test:
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: run
        run: |
            cargo run
      - name: test
        run: |
            cargo test
